/*
 Navicat Premium Data Transfer

 Source Server         : Remoto
 Source Server Type    : MariaDB
 Source Server Version : 100512
 Source Host           : 35.236.255.86:3306
 Source Schema         : ithuimanguillo

 Target Server Type    : MariaDB
 Target Server Version : 100512
 File Encoding         : 65001

 Date: 16/08/2021 22:06:37
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for grupos
-- ----------------------------
DROP TABLE IF EXISTS `grupos`;
CREATE TABLE `grupos`  (
  `idgrupo` int(11) NOT NULL AUTO_INCREMENT,
  `idciclo` int(11) NOT NULL,
  `num_semestre` int(11) NULL DEFAULT NULL,
  `idcarrera` int(11) NOT NULL,
  `idmateria` int(11) NOT NULL,
  `idprofesor` int(11) NOT NULL,
  `desc_grupo_corto` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `desc_grupo` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `aula` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `fecha_envio_acta` datetime NULL DEFAULT NULL,
  `horario` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `lunes` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `martes` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `miercoles` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `jueves` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `viernes` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `sabado` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`idgrupo`) USING BTREE,
  INDEX `fk_grupos_ciclo1_idx`(`idciclo`) USING BTREE,
  INDEX `fk_grupos_profesores1_idx`(`idprofesor`) USING BTREE,
  INDEX `fk_grupos_cat_materias1_idx`(`idmateria`) USING BTREE,
  INDEX `fk_grupos_cat_carreras1_idx`(`idcarrera`) USING BTREE,
  CONSTRAINT `fk_grupos_cat_carreras1` FOREIGN KEY (`idcarrera`) REFERENCES `cat_carreras` (`idcarrera`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_cat_materias1` FOREIGN KEY (`idmateria`) REFERENCES `cat_materias` (`idmateria`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_ciclo1` FOREIGN KEY (`idciclo`) REFERENCES `ciclo` (`idciclo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_profesores1` FOREIGN KEY (`idprofesor`) REFERENCES `profesores` (`idprofesor`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 73 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of grupos
-- ----------------------------
INSERT INTO `grupos` VALUES (1, 1, NULL, 3, 1, 16, 'A', 'VI A IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (2, 1, NULL, 3, 2, 16, 'A', 'II A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (3, 1, NULL, 2, 3, 9, 'A', 'IV A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (4, 1, NULL, 3, 4, 7, 'A', 'VIII A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (5, 1, NULL, 3, 5, 7, 'A', 'VIII A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (6, 1, NULL, 3, 6, 7, 'A', 'VI A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (7, 1, NULL, 1, 7, 8, 'A', 'IV A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (8, 1, NULL, 3, 8, 8, 'A', 'II A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (9, 1, NULL, 3, 9, 7, 'A', 'IV A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (10, 1, NULL, 3, 10, 7, 'A', 'IV A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (11, 1, NULL, 3, 11, 16, 'A', 'II A IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (12, 1, NULL, 3, 12, 16, 'A', 'VI A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (13, 1, NULL, 3, 13, 21, 'A', 'VIII A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (14, 1, NULL, 3, 14, 21, 'A', 'VIII A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (15, 1, NULL, 2, 15, 15, 'A', 'IV A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (16, 1, NULL, 2, 16, 15, 'A', 'VI A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (17, 1, NULL, 4, 17, 15, 'A', 'II A IPET MIXTA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (18, 1, NULL, 4, 18, 15, 'A', 'II A IPET MIXTA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (19, 1, NULL, 3, 18, 2, 'A', 'II A   IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (20, 1, NULL, 2, 19, 2, 'A', 'IV A   ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (21, 1, NULL, 1, 20, 25, 'A', 'IV A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (22, 1, NULL, 3, 21, 19, 'A', 'IV A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (23, 1, NULL, 1, 22, 19, 'A', 'II A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (24, 1, NULL, 2, 23, 19, 'A', 'II A  ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (25, 1, NULL, 3, 23, 19, 'A', 'II A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (26, 1, NULL, 4, 24, 5, 'A', 'II A IPET MIXTA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (27, 1, NULL, 2, 25, 5, 'A', 'VIII A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (28, 1, NULL, 2, 26, 5, 'A', 'VIII A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (29, 1, NULL, 3, 24, 5, 'A', 'II A IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (30, 1, NULL, 2, 27, 25, 'A', 'VI A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (31, 1, NULL, 2, 28, 25, 'A', 'V A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (32, 1, NULL, 3, 29, 25, 'A', 'IV A IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (33, 1, NULL, 2, 30, 11, 'A', 'II A  ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (34, 1, NULL, 2, 31, 3, 'A', 'IV A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (35, 1, NULL, 2, 32, 3, 'A', 'IV A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (36, 1, NULL, 2, 33, 3, 'A', 'VI A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (37, 1, NULL, 2, 34, 3, 'A', 'VIII A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (38, 1, NULL, 1, 35, 18, 'A', 'VI A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (39, 1, NULL, 1, 36, 18, 'A', 'II A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (40, 1, NULL, 1, 37, 18, 'A', 'VI A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (41, 1, NULL, 2, 38, 13, 'A', 'IV A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (42, 1, NULL, 2, 39, 13, 'A', 'VIII A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (43, 1, NULL, 1, 12, 13, 'A', 'VIII A IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (44, 1, NULL, 1, 40, 12, 'A', 'II A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (45, 1, NULL, 1, 41, 12, 'A', 'II A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (46, 1, NULL, 1, 42, 12, 'A', 'VI A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (47, 1, NULL, 3, 43, 17, 'A', 'IV A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (48, 1, NULL, 1, 44, 17, 'A', 'VI A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (49, 1, NULL, 2, 45, 4, 'A', 'II A  ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (50, 1, NULL, 3, 46, 17, 'A', 'IV A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (51, 1, NULL, 1, 47, 17, 'A', 'II A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (52, 1, NULL, 2, 48, 4, 'A', 'IIA  ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (53, 1, NULL, 2, 49, 4, 'A', 'VI A  ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (54, 1, NULL, 3, 50, 4, 'A', 'VI A  IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (55, 1, NULL, 2, 51, 10, 'A', 'II A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (56, 1, NULL, 2, 52, 10, 'A', 'VI A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (57, 1, NULL, 2, 53, 10, 'A', 'VIII A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (58, 1, NULL, 2, 54, 10, 'A', 'VIII A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (59, 1, NULL, 1, 55, 1, 'A', 'IV A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (60, 1, NULL, 1, 56, 1, 'A', 'IV A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (61, 1, NULL, 1, 57, 1, 'A', 'VI A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (62, 1, NULL, 1, 58, 1, 'A', 'VI A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (63, 1, NULL, 1, 59, 20, 'A', 'IV A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (64, 1, NULL, 1, 60, 24, 'A', 'VI A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (65, 1, NULL, 1, 61, 24, 'A', 'VI A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (66, 1, NULL, 1, 62, 24, 'A', 'VI A  IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (67, 1, NULL, 3, 63, 9, 'A', 'IV A IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (68, 1, NULL, 3, 64, 9, 'A', 'VI A IPET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (69, 1, NULL, 2, 65, 22, 'A', 'IV A  ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (70, 1, NULL, 2, 66, 23, 'A', 'VIII A ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (71, 1, NULL, 2, 67, 2, 'A', 'VI A   ILOG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `grupos` VALUES (72, 1, NULL, 1, 68, 2, 'A', 'II A   IIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
